apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishub2aks-6810"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishub2aks-6810"
  template:
    metadata:
      labels:
        app: "aaaatiwarishub2aks-6810"
    spec:
      containers:
        - name: "aaaatiwarishub2aks-6810"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishub2aks6810"
          ports:
          - containerPort: 4000