apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishub2aks-65b0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishub2aks-65b0"
  template:
    metadata:
      labels:
        app: "aaaatiwarishub2aks-65b0"
    spec:
      containers:
        - name: "aaaatiwarishub2aks-65b0"
          image: "aaaatiwarishubaksacrm.azurecr.io/aaaatiwarishub2aks65b0"
          ports:
          - containerPort: 4000