apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-d05c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-d05c"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-d05c"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-d05c"
          image: "aaaaaatiwaishubacr7.azurecr.io/aaaaatiwarishubaksc167"
          ports:
          - containerPort: 4000