apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishubaks-46e9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishubaks-46e9"
  template:
    metadata:
      labels:
        app: "aatiwarishubaks-46e9"
    spec:
      containers:
        - name: "aatiwarishubaks-46e9"
          image: "aatiwarishubaksacr5.azurecr.io/aatiwarishubaks46e9"
          ports:
          - containerPort: 4000