apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-e3ed"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-e3ed"
  template:
    metadata:
      labels:
        app: "akskodey-e3ed"
    spec:
      containers:
        - name: "akskodey-e3ed"
          image: "l5aks.azurecr.io/akskodeye3ed"
          ports:
          - containerPort: 4000