apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaabugbashprovsvcrouting-e580"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaabugbashprovsvcrouting-e580"
  template:
    metadata:
      labels:
        app: "aaaaabugbashprovsvcrouting-e580"
    spec:
      containers:
        - name: "aaaaabugbashprovsvcrouting-e580"
          image: "diaggarwregistry.azurecr.io/aaaaabugbashprovsvcroutinga9d2"
          ports:
          - containerPort: 4000