apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishub2aks-db0e"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishub2aks-db0e"
  template:
    metadata:
      labels:
        app: "aaaatiwarishub2aks-db0e"
    spec:
      containers:
        - name: "aaaatiwarishub2aks-db0e"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishub2aksdb0e"
          ports:
          - containerPort: 4000