apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishubaks-4f7e"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishubaks-4f7e"
  template:
    metadata:
      labels:
        app: "aatiwarishubaks-4f7e"
    spec:
      containers:
        - name: "aatiwarishubaks-4f7e"
          image: "aaaatiwarishubregistry.azurecr.io/aatiwarishubaks4f7e"
          ports:
          - containerPort: 4000