apiVersion: v1
kind: Service
metadata:
    name: "akskodey-48b4"
    labels:
        app: "akskodey-48b4"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "akskodey-48b4"