apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishubaks2-0c01"
    labels:
        app: "aaaatiwarishubaks2-0c01"
spec:
    type: ClusterIP
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishubaks2-0c01"
