apiVersion: v1
kind: Service
metadata:
    name: "aatiwarishubaks-49cc"
    labels:
        app: "aatiwarishubaks-49cc"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aatiwarishubaks-49cc"