apiVersion: v1
kind: Service
metadata:
    name: "aaaaatiwarishubaks-4e77"
    labels:
        app: "aaaaatiwarishubaks-4e77"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaaatiwarishubaks-4e77"