apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishub2aks-6810"
    labels:
        app: "aaaatiwarishub2aks-6810"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishub2aks-6810"