apiVersion: v1
kind: Service
metadata:
    name: "aaaaabugbashprovsvc-0d42"
    labels:
        app: "aaaaabugbashprovsvc-0d42"
spec:
    type: ClusterIP
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaaabugbashprovsvc-0d42"
