on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET_65b0}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aaaatiwarishubaksacrm -g aaaatiwarishubaksacrma2cc-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aaaatiwarishubaksacrm --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aaaatiwarishubaksacrm --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aaaatiwarishubaksacrm --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubaksacrm.azurecr.io
        username: ${{steps.create-acr.outputs.acr_username}}
        password: ${{steps.create-acr.outputs.acr_password}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t aaaatiwarishubaksacrm.azurecr.io/aaaatiwarishub2aks65b0:${{github.sha}}
        docker push aaaatiwarishubaksacrm.azurecr.io/aaaatiwarishub2aks65b0:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_aaaatiwarishub2aks_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aaaatiwarishub2aks65b0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aaaatiwarishub2aks65b0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aaaatiwarishub2aks65b0
        container-registry-url: aaaatiwarishubaksacrm.azurecr.io
        container-registry-username: ${{steps.create-acr.outputs.acr_username}}
        container-registry-password: ${{steps.create-acr.outputs.acr_password}}
        secret-name: aaaatiwarishdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aaaatiwarishub2aks65b0
        manifests: |
          ./manifests/deployment-65b0.yml
          ./manifests/service-65b0.yml
        images: |
          aaaatiwarishubaksacrm.azurecr.io/aaaatiwarishub2aks65b0:${{github.sha}}
        imagepullsecrets: |
          aaaatiwarishdockerauth