on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{secrets.acr_aaaatiwarishubregistry_username}}
        password: ${{secrets.acr_aaaatiwarishubregistry_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t aaaatiwarishubregistry.azurecr.io/aatiwarishubaks0a9c:${{ github.sha }}
        docker push aaaatiwarishubregistry.azurecr.io/aatiwarishubaks0a9c:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_aatiwarishubaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aatiwarishubaks0a9c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aatiwarishubaks0a9c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aatiwarishubaks0a9c
        container-registry-url: aaaatiwarishubregistry.azurecr.io
        container-registry-username: ${{secrets.acr_aaaatiwarishubregistry_username}}
        container-registry-password: ${{secrets.acr_aaaatiwarishubregistry_password}}
        secret-name: aatiwarishubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aatiwarishubaks0a9c
        manifests: |
          ./manifests/deployment-0a9c.yml
          ./manifests/service-0a9c.yml
        images: |
          aaaatiwarishubregistry.azurecr.io/aatiwarishubaks0a9c:${{ github.sha }}
        imagepullsecrets: |
          aatiwarishubdockerauth